const express = require('express')
const {Login,getprofile} = require('../controller/LoginController')
const {changePassword,customIdAndPassword, checkPublishOrNot, reset} = require('../controller/ChangePasswordController')
const Authverify = require('../middleware/AuthVerify')
const { requestOtp, verifyOtpandSignup } = require('../controller/OtpController')
const rateLimitMiddleware = require('../middleware/changePasswordLimit')
const router = express.Router()

router.post('/verifyotp',verifyOtpandSignup)
router.post('/sendOtp',requestOtp)
router.post('/login',Login)
router.post('/changepassword',Authverify,changePassword)
router.get('/getprofile',getprofile)
router.post('/setpass',customIdAndPassword)
router.post('/checkpublish',checkPublishOrNot)
router.post('/changeCustom',rateLimitMiddleware,reset)
module.exports=router