const express = require('express')
const {Login,getprofile} = require('../../controller/LoginController')
const {changePassword,customIdAndPassword, checkPublishOrNot, reset, checkPublishOrNotTdm, customIdAndPasswordtdm, resettdm} = require('../../controller/ChangePasswordController')
const Authverify = require('../../middleware/AuthVerify')
const { requestOtp, verifyOtpanduser, resetPassword, resetOtpVerify } = require('../../controller/OtpController')
const rateLimitMiddleware = require('../../middleware/changePasswordLimit')
const {updateProfile,pubgprofile, freefireprofile, uploadImage, uploadimage, uploadproofclash, uploadprooftdm} = require('../../controller/updateProfileController')
const router = express.Router()
const{storage,multer}=require('../../middleware/multer')
const upload = multer({storage:storage})
router.post('/verifyotp',verifyOtpanduser)
router.post('/sendOtp',requestOtp)
router.post('/login',Login)
router.post('/changepassword',Authverify,changePassword)
router.get('/getprofile',Authverify,getprofile)
router.post('/setpass',customIdAndPassword)
router.post('/setpasstdm',customIdAndPasswordtdm)
router.post('/checkpublish',checkPublishOrNot)
router.post('/checkpublishtdm',checkPublishOrNotTdm)
router.post('/changeCustom',Authverify,reset)
router.post('/changeCustomtdm',Authverify,resettdm)
router.post('/updateprofile',Authverify,updateProfile)
router.post('/upload', upload.single('image'),uploadImage)
router.post('/imageset',Authverify,uploadimage)
router.post('/uploadproof',Authverify,uploadproofclash)
router.post('/uploadprooftdm',Authverify,uploadprooftdm)
router.post('/freefirename',Authverify,freefireprofile)
router.post('/pubgname',Authverify,pubgprofile)
router.post('/forgetpassword',resetPassword)
router.post('/verifyforgetpassword',resetOtpVerify)
module.exports=router