const express = require('express')
const {checkResult,checkuserJoinFF} = require('../../controller/checkResultController')
const Authverify = require('../../middleware/AuthVerify')
const {deleteCard,deleteCardtdm, reportClashSquad, reportTdm} = require('../../controller/DeleteMatchCardController')
const router3 = express.Router()
router3.post('/deletecard',Authverify,deleteCard)
router3.post('/deletecardtdm',Authverify,deleteCardtdm)
router3.post('/reportClash',Authverify,reportClashSquad)
router3.post('/reportTdm',Authverify,reportTdm)
module.exports = router3