const express = require('express')
const Authverify = require('../../middleware/AuthVerify')
const { checkuserJoinPubg, joinuserPubg, getpubgMatch, createPubgMatch, addName, createtdm, gettdm, joinuserPubgtdm, addNametdm, checkuserJoinPubgtdm } = require('../../controller/PubgJoinUserController')
const router = require('./AuthenticateRouter')
const router4 = express.Router()
router4.post('/joinuserPubg',Authverify,joinuserPubg)
router4.post('/joinuserPubgtdm',Authverify,joinuserPubgtdm)
router4.post('/checkuserPubg',Authverify,checkuserJoinPubg)
router4.post('/checkuserPubgtdm',Authverify,checkuserJoinPubgtdm)
router4.post('/creatematch',Authverify,createPubgMatch)
router4.post('/creatematchtdm',createtdm)
router4.get('/getpubg',getpubgMatch)
router4.get('/gettdm',gettdm)
router4.post('/addName',Authverify,addName)
router4.post('/addNametdm',Authverify,addNametdm)
module.exports = router4